name: JSON and Dockerfile linter

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-docker-v20:
    name: Docker v20.10 Compatibility
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0    
    
    - uses: github/super-linter/slim@v4
      env:
        VALIDATE_ALL_CODEBASE: true,
        DEFAULT_BRANCH: main,
        FILTER_REGEX_INCLUDE: '^src/.*\.json$|^src(/.*)?/\.devcontainer/.*\.json$|^src(/.*)?/\.devcontainer/(Dockerfile.*|.*\.dockerfile)$',
        VALIDATE_DOCKERFILE: true,
        VALIDATE_JSON: true
        
